---
#- name: Hello World!
#  hosts: all
# 
#  tasks:
# 
#  - name: Hello World!
#    shell: echo "Hi! Tower is working."


- name: Update the system
  hosts: all
  tasks:
  become: yes
  ansible.builtin.apt:
    update_cache: yes
  tags:
  - update

