---
- name: Update the system
  hosts: all
  tasks:
  become: yes
  shell: echo "Hi! Tower is working."
  # apt:
    # update_cache: yes
  tags:
  - update


#- name: Hello World!
#  hosts: all
# 
#  tasks:
# 
#  - name: Hello World!
#    shell: echo "Hi! Tower is working."


